### PR TITLE
CI: Remove pytest wrapper .ci/tests.sh

### PR DESCRIPTION
**Pull request by jayvdb**
Removes pytest wrapper .ci/tests.sh, and .ci/env_variables.sh
which was only used by .ci/tests.sh.

Combined they only controlled whether `--doctest-modules` would
be added to the pytest command line, but it is already part of
the `addopts` in setup.py, so this had no effect at all.

Closes https://github.com/coala/coala-quickstart/issues/111
Related to https://github.com/coala/coala-quickstart/issues/106

### CODE REVIEW

**Comment by jayvdb** [comment]
Note also that there is only one problem with the doctests on Windows, as found and fixed at https://github.com/coala/coala-quickstart/pull/98

**Comment by satwikkansal** [comment]
I tried to add Appveyor on top of this PR and the build was successful :) https://ci.appveyor.com/project/satwikkansal/coala-quickstart/build/job/fefbpw5lmhsjdnwk

**Comment by jayvdb** [comment]
This commit isnt needed for your Appveyor PR; this commit only proves that your Appveyor PR doesnt benefit from using tests.sh , etc.  Anyway ... can I has acks??

**Comment by satwikkansal** [comment]
> This commit isnt needed for your Appveyor PR; this commit only proves that your Appveyor PR doesnt benefit from using tests.sh.

Yes, the command `bash .ci/tests.sh` in `appveyor.yml` was causing problem in my earlier Appveyor PR because tests.sh used `python3`. I replaced it with `pytest` and now it works. Sorry for the confusion and thanks for the PR :)

**Comment by satwikkansal** [comment]
ack  	c846dc1

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack c846dc1

**Pull request merged**
