### PR TITLE
Activate bears for test files and fix styling mistakes

### PR DESCRIPTION
**Pull request by satwikkansal**

### CODE REVIEW

**Comment by satwikkansal** [comment]
Oops, added `.coafile` in one commit and fixed the styling mistakes in another which made Gitmate angry initially :P

**Comment by hemangsk** [comment]
In the commit message its,  "Closes to <issue_number>" , extra 'to' in between is not required I think, rest LGTM :)

**Comment by nkprince007** [comment]
Yeah, @satwikkansal just amend the commit message to:
```bash
Closes #113
```
rest LGTM :)

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-quickstart/pull/123/commits/9fc657b3216ddb7996e225847bec9700b93e00f2

**Comment by Asnelchristian** [comment]
just rebase and we merge :) :+1:

**Comment by satwikkansal** [comment]
reack 7ac90f0

**Comment by satwikkansal** [comment]
@Asnelchristian rebased :)

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
