### PR TITLE
green_mode: Choose job count based on environment

### PR DESCRIPTION
**Pull request by jayvdb**
Python 3.4 and 3.5 fail under our pytest configuration
when the number of jobs is the cpu count - 1.
On Python 3.4, an extra cpu needs to be reserved for the tests
to operate smoothly on CI, and on Python 3.5 and Windows,
multiprocessing needs to be disabled entirely.

Expose argument jobs throughout green_mode, so that it
can be also exposed to the user or test suite for more
controlled use and testing.

Related to https://github.com/coala/coala-quickstart/issues/295

### CODE REVIEW

**Comment by jayvdb** [comment]
Depends on https://gitlab.com/coala/mobans/merge_requests/86 to pass the moban job

**Comment by satwikkansal** [comment]
Feels great to see everything green after a long time :p

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-quickstart/pull/296/commits/4e801867d733c94d651034a3d4df8cbd4a3b6430

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
