### PR TITLE
Add .editorconfig file

### LINKED ISSUE #190: Add .editorconfig file
Our style follows the example given on http://editorconfig.org/ for Python and YAML
label: difficulty/low initiatives/gci
Opened by @mohitkyadav at [Gitter](https://gitter.im//mohitkyadav?at=5a07259c540c78242def89fe)

### PR DESCRIPTION
**Pull request by jackthepirate6**
This adds .editorconfig file for coala-quickstart.

closes #190

### CODE REVIEW

**Comment by ishanSrt** [comment]
Redundant commit body, same as shortlog. Might as well remove it. Also fullstop is expected in commit body.

**Comment by khanchi97** [comment]
use uppercase C in `Closes #xyz` in your commit message ;)

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Blocked by https://github.com/coala/coala-quickstart/issues/216

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-quickstart/pull/213/commits/eca9c62ebe558bd94d531a831517e7ae8311d238

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
