### PR TITLE
Replace PEP8Bear with PycodestyleBear

### PR DESCRIPTION
**Pull request by Abhisek-**
Change the important Bear for python language from
PEP8Bear to PycodestyleBear

Closes https://github.com/coala/coala-quickstart/issues/53

### CODE REVIEW

**Comment by Abhisek-** [comment]
should I change something else ?

**Comment by Mariatta** [comment]
You need to change the footer of your commit message.
From Fixes 53 into Closes 53.

The keyword Fixes is for fixing bugs.
Your issue is not considered a bug.

Thanks :)

**Comment by Abhisek-** [comment]
Oh I see. Thanks @Mariatta

**Comment by jayvdb** [comment]
ack 99007e5

**Comment by Abhisek-** [comment]
I'm not with my computer now. Will do it 👍

**Comment by Mariatta** [comment]
unack 99007e5

**Comment by Mariatta** [comment]
ack cef39e3

**Comment by Mariatta** [comment]
@rultor merge

**Pull request merged**
