### PR TITLE
README.rst: Fix a typo

### PR DESCRIPTION
**Pull request by sirtetris**
Change "you will want do" to "you will want to"

Closes https://github.com/coala/coala-quickstart/issues/81

### CODE REVIEW

**Comment by satwikkansal** [comment]
@sirtetris Appveyor build is failing for some unknown reason. Re-triggering the PR will likely solve the problem. Can you please retrigger the PR by doing `git commit --amend` and then force push.

**Comment by IpshitaC** [comment]
ack 472900399a5b5de677863b6889a16ad6a4bcc6a8

**Comment by Nosferatul** [comment]
ack 4729003

**Comment by Nosferatul** [comment]
@rultor merge

**Pull request merged**
