### PR TITLE
constants.py: removed 'coalabear'

### PR DESCRIPTION
**Pull request by venkateshbellale**
merging this issue with  master branch

### CODE REVIEW

**Comment by sims1253** [comment]
hey can you take a look at http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and rework your commit message accordingly?

Just git commit --amend
change the message
and push --force to update

**Comment by venkateshbellale** [comment]
constants.py: removed  'coalabear'

This fix doesn't enables coalabear .

Fixes https://github.com/coala/coala-quickstart/issues/44

**Comment by jayvdb** [comment]
That looks like a good message to use.

Now do `git commit --amend` , and then replace your current commit message with that message.

And then `git push --force myfork`

**Comment by jayvdb** [comment]
The filename is case sensitive, so the commit message should be `Constants.py ` not `constants.py`.

'removed' is flagged as a bad word for a commit message first line, as it is not imperative mood.

So, amend your commit message first line to be: `Constants.py: Deactivate coalaBear`

**Comment by andreidinu** [comment]
@venkateshbellale are you still working on this?

**Comment by venkateshbellale** [comment]
sorry for that ,I was having my school exams because of that I was  not able to work on this,but now as they are over ,I will  wrap this up.

**Comment by jayvdb** [comment]
Do you want to re-claim that GCI task, and finish this over the weekend before the end of GCI?

**Comment by jayvdb** [comment]
please rebase your changes.  see your `git log` vs https://github.com/coala/coala-quickstart/commits/master

**Comment by adtac** [comment]
Also, in the commit message, there shouldn't be a space between `Constants` and the colon.

**Comment by jayvdb** [comment]
Done in https://github.com/coala/coala-quickstart/pull/74

**Pull request closed without merging**
