### PR TITLE
.gitignore: Add .DS_Store

### PR DESCRIPTION
**Pull request by radonys**
.DS_Store files don't contain any information relevant to others.

Closes https://github.com/coala/coala-quickstart/issues/198

### CODE REVIEW

**Comment by prnvdixit** [comment]
Also, ignore "approved" - It was accidental :sweat_smile:.... 
Some problem with GitMate (not from your side) and an issue with codecov is still there :confused:

**Comment by ishanSrt** [comment]
@radonys I really have no idea why's that happening. It also say that 

> Oops.. GitMate broke down. :( 

What I can suggest is, use `git commit --amend` and then force push (after slightly modifying your commit message) so that the checks run again on your commit. Please do it without closing and making another PR.

**Comment by radonys** [comment]
@ishanSrt Thanks. I think a manual review is remaining.

**Comment by ishanSrt** [comment]
ack https://github.com/coala/coala-quickstart/pull/205/commits/6512174bd8be7256ba84320a749f6b1ac79a1112

**Comment by amisha2016** [comment]
One can view it at [https://amisha.gdy.club/coala/docs/_build/html/Developers/Newcomers_Guide.html#optional-get-help-with-git](url)

**Comment by radonys** [comment]
@amisha2016. Thanks for the link. But it seems that the link is not working. Please check. Secondly, the PR is pretty well this time. Only maintainers need to verify it now.

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
