### PR TITLE
Preinstall packaging

### LINKED ISSUE #210: AppVeyor Build failing most of the times for the same code for which it had passed earlier
error log doesn't show anything wrong or failing, shows 
```
======================== 56 passed in 60.93 seconds ==========================
Command exited with code 1
```
importance/high

link: https://ci.appveyor.com/project/coala/coala-quickstart/build/1.0.267

### LINKED ISSUE #229: `packaging` version conflicts
coala-bears in pre-release depend on safety module, which in turn dictates that latest packaging version be installed in it's [setup.py](https://github.com/pyupio/safety/blob/1380740696100a5724c4f33c735df9364de77ddf/setup.py#L15)
Whereas coala version in pre-release requires packaging version to be compatible with 16.8

Thus when pip would generate a dependency graph, the selection of packaging version would be arbitrary
Leading to random failures

safety module doesn't really need packaging's latest version, so we can safely pin it to 16.8 for current purposes

Although we need to change this with the next coala-bears pre-release.

### PR DESCRIPTION
**Pull request by virresh**
Fixes #229,
#228
and
Closes #210

### CODE REVIEW

**Comment by virresh** [comment]
Sure, I'll separate them into two commits 
Also me and @ishanSrt triaged the issue yesterday night after a long spammy conversation, and believe that this one [relates](https://github.com/coala/coala-quickstart/issues/229#issuecomment-390522897) to https://github.com/coala/coala-quickstart/issues/210, It is possible that we are wrong in that conclusion, but Appveyor also experiences some network glitches and it might fail due to one of them. Though cannot definitely say this will fix those kind of failures.

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
So this is interesting ... https://travis-ci.org/jayvdb/coala-quickstart/jobs/384356347 ... reverting this commit also works :P

**Comment by virresh** [comment]
@jayvdb 
Can you retry the build without caches ?


> Leading to random failures

iirc the issue is randomly occuring because of the way how pip downloads the dependencies of packages listed in requirements.txt ...

**Comment by jayvdb** [comment]
That was a build without any caches on Travis.  Rebuilding Circle without cache at https://circleci.com/gh/jayvdb/coala-quickstart/29 .  But yes, I forgot this was an intermittent thing.

**Pull request merged**
