### PR TITLE
Generate all instead of default section

### PR DESCRIPTION
**Pull request by sils**
Fixes https://github.com/coala/coala-quickstart/issues/127

### CODE REVIEW

**Comment by sils** [comment]
CC @satwikkansal @hemangsk I don't at all understand why this hasn't happened yet, it's super simple and we have deprecated the default section since the last release which is over a month ago meaning since a month coala-quickstart generates useless deprecated syntax.

**Comment by hemangsk** [comment]
ack

**Comment by hemangsk** [comment]
ack af9d062

**Comment by hemangsk** [comment]
Continued in https://github.com/coala/coala-quickstart/pull/156 with permission from @sils (commit author)

**Comment by sils** [comment]
closing this then

**Pull request closed without merging**
