### PR TITLE
EditorconfigParsing.py: Correct function name

### PR DESCRIPTION
**Pull request by ishanSrt**
Closes https://github.com/coala/coala-quickstart/issues/223

### CODE REVIEW

**Comment by jayvdb** [comment]
blocked by broken CI.
I cant even see issues raised about these CI problems.

**Comment by jayvdb** [comment]
Does that mean we dont have test coverage of this?
Can tests be added?

**Comment by satwikkansal** [comment]
Adding tests would require proper understanding of all the regexes involved. This snippet of code was taken from https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Project.py#L49, and I'm not sure what's the best way to deal with testing such scenarios. We can have a look at the tests at editorconifg's repo, and imitate them here, or we just keep it the way it is right now.

This issue occurred because I changed the function name and forgot to change it in the recursive calls. Logic wise the code is same as https://github.com/coala/coala-quickstart/blob/master/coala_quickstart/generation/Project.py#L49

**Comment by ishanSrt** [comment]
created issue https://github.com/coala/coala-quickstart/issues/232

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-quickstart/pull/225/commits/9d52cb1b4595a56f863c7a9593b85cc4b9da4998

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
