### PR TITLE
Drop Python 3.3 support

### PR DESCRIPTION
**Pull request by adtac**
Closes https://github.com/coala/coala-quickstart/issues/35

### CODE REVIEW

**Comment by sils1297** [comment]
please also remove the circleci conf, just grep for `3.3`

**Comment by adtac** [comment]
@sils1297 done :+1:

**Comment by adtac** [comment]
Lol, wrong fixes message ID. Fixed :+1:

**Comment by sils1297** [comment]
ack https://github.com/coala/coala-quickstart/pull/36/commits/2f76455e793e29628dfafbaeec632f4db1d4dd3d

**Comment by sils1297** [comment]
was there any other CI here?

**Comment by adtac** [comment]
Nope, just circle. There's an issue to add Appveyor later, but for now, that's it.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
changing circle from 3 to 2 builds then to increase parallelization

**Pull request merged**
