### PR TITLE
Replace coalib.misc.ContextManagers with coala_utils.ContextManagers

### PR DESCRIPTION
**Pull request by Abhisek-**
Replaced import statements in
* test/generation/Bears.py
* test/generation/FileGlobs.py
* test/generation/Project.py
* tests/interaction/Logo.py
with corresponding from coala_utils.ContextManagers

Fixes https://github.com/coala/coala-quickstart/issues/54

### CODE REVIEW

**Comment by Abhisek-** [comment]
should I change the commit message or the comment here or both ?

**Comment by Mixih** [comment]
Just the commit is necessary though the comment helps out the reviewers so you could do that too.

**Comment by Mixih** [comment]
ack 52be587

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
