### PR TITLE
rultor: Check maintainership before merging

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by satwikkansal** [comment]
Rebase required for Appveyor to pass :)

**Comment by satwikkansal** [comment]
@adtac Rebase please :)

**Comment by adtac** [comment]
There's a gitmate command to do that, right? :D Rebased :+1:

**Comment by satwikkansal** [comment]
CircleCI is failing :(, you'll need to trigger a rebuild I guess.

**Comment by Vedarth** [comment]
unack https://github.com/coala/coala-quickstart/pull/162/commits/816ecb49204c30fa70dc90fc5265eb5a6fbe4806

**Comment by adtac** [comment]
This is from back when we used rultor and no longer valid.

**Pull request closed without merging**
