### PR TITLE
README.rst: Fix spelling

### PR DESCRIPTION
**Pull request by RonnanSouza**
I change 'do' -> 'to' at the README file

Closes https://github.com/coala/coala-quickstart/issues/81

### CODE REVIEW

**Comment by Udayan12167** [comment]
For 1bfecd1 I think `Readme.rst: Fix spelling` would be better.

**Comment by Udayan12167** [comment]
In your commit body of db88792 it also contains the change description for 1bfecd1. Please fix that.

**Comment by RonnanSouza** [comment]
@Udayan12167  How can I fix that, if I already commited it?

**Comment by Udayan12167** [comment]
What is the db88792 commit doing? Is it removing a trailing whitespace? I think it is an unnecessary commit or is referencing the wrong issue.

**Comment by Udayan12167** [comment]
@RonnanSouza look into `git rebase`

**Comment by RonnanSouza** [comment]
@Udayan12167 I'm sorry brow, it's my first time, and I'm really lost, so I'll delete the pull request and try to do it correctly.

**Comment by RonnanSouza** [comment]
@Udayan12167 It's my first-time brow, sorry.

**Pull request closed without merging**
