### PR TITLE
.coafile: Add YAMLLintBear

### LINKED ISSUE #121: Check repository for .yml files using YAMLLintBear
Add YAMLLintBear in .coafile and fix .yml file issues raised by coala. See https://github.com/coala/coala-bears/pull/1799 for reference.
difficulty/newcomer

Opened via [gitter](https://gitter.im/coala/coala/?at=5945c7c4f31c8ced0c479732) by @Monal5031

### PR DESCRIPTION
**Pull request by mohitkyadav**
Add YAMLLintBear in .coafile
and fix issues raised by coala
Fixes #121

### CODE REVIEW

**Comment by Monal5031** [comment]
@mohitkyadav Break your commit message in more lines only 50 chars are allowed per line.

**Comment by Monal5031** [comment]
ack 9700f80

**Comment by Monal5031** [comment]
@mohitkyadav Please edit your commit message to only:
```
Add YAMLLintBear in .coafile and
fix issues raised afer running coala.
Fixes #121
```

**Comment by Monal5031** [comment]
reack 28fa9e8

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
