### PR TITLE
ISSUE_TEMPLATE.md: Add template

### PR DESCRIPTION
**Pull request by utkarsh2102**
This PR adds an issue template, incorporating the changes asked in PR #239.

Closes https://github.com/coala/coala-quickstart/issues/187

### CODE REVIEW

**Comment by jayvdb** [comment]
@utkarsh2102 , you were told at https://gitter.im/coala/coala?at=5b0ede2616f6496124f26010 to not close PRs.

**Comment by jayvdb** [comment]
I've removed you from @coala organisation, and unassigning you from issues.  Once you have a bit more experience, come back again.

**Comment by jayvdb** [comment]
Reassigned as this is the first occasion, even thought it just occurred.

**Comment by utkarsh2102** [comment]
@palash25, made changes as required.
@jayvdb, please tell me if any ore changes required?

**Comment by jayvdb** [comment]
ack b174993

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-quickstart/pull/251/commits/21476d4fa18ae7cd632ed44d5684c5910cf82770

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
